### ISSUE TITLE
Version inconsistencies

### ISSUE THREAD

**Issue by ThatDMGuy** [ImNotJahan/danmachi-mod#3]
When using the 1.2.0 jar it shows up as 1.1.2 inside minecraft.
![image](https://user-images.githubusercontent.com/92564057/137432661-ba76bef8-2de6-4d35-8f2d-be404b236a9f.png)
![image](https://user-images.githubusercontent.com/92564057/137432594-6c9a798f-d4c4-463e-bd02-f8e7551d6eb6.png)

Additionally, the pack_format is set to 4.
![image](https://user-images.githubusercontent.com/92564057/137432725-2c96e693-41ba-4ddf-be36-0a537cb82916.png)

This leads it to say that the datapack is outdated when in game.
![image](https://user-images.githubusercontent.com/92564057/137432826-5419b5dd-c23a-4298-96a4-968dc96cf491.png)
![image](https://user-images.githubusercontent.com/92564057/137432805-06822d5c-ee94-48bb-bc00-12dee04dbb78.png)

**Comment by ImNotJahan** [comment]
Done in 1.16.4-1.2.1 & the version will be changed correctly in the future
